version: '3.9'

services:
  database:
    image: mariadb
    container_name: database
    ports:
    - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password

volumes:
  db_data: